- hosts: nts-active
  strategy: free
  gather_facts: no
  become: true
  become_user: root
  vars:
    directories_to_check:
      - { directory: '/opt/traceroute/result_traceroute/', time: '-60' }

  roles:
    - database
