- hosts: remote
  strategy: free
  gather_facts: no
  become: true
  become_user: root
  vars:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0664
    directory:
      - { src: '/$HOME/ansible/database/{{var}}', dest: '/opt/database/database.ini' }
      - { src: '/$HOME/ansible/database/{{var}}', dest: '/opt/api/database.ini' }
      - { src: '/$HOME/ansible/database/{{var}}', dest: '/opt/traceroute/database.ini' }
      - { src: '/$HOME/ansible/database/{{var}}', dest: '/opt/ping_exporter/database.ini' }

  roles:
    - database
