- hosts: edge
  strategy: free
  gather_facts: no
  become: true
  become_user: root
  vars:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0664
    directory:
      - { src: '/$HOME/ansible/pingtest/{{var}}', dest: '/opt/ping_exporter/config.ini' }

  roles:
    - pingtest
