- hosts: remote
  strategy: free
  gather_facts: no
  become: true
  become_user: root
  vars:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0664
    directory:
      - { src: '/$HOME/ansible/pingtest/{{var1}}', dest: '/etc/prometheus/targets1.yml' }
      - { src: '/$HOME/ansible/pingtest/{{var2}}', dest: '/etc/prometheus/targets2.yml' }
      - { src: '/$HOME/ansible/pingtest/{{var3}}', dest: '/etc/prometheus/targets3.yml' }
      - { src: '/$HOME/ansible/pingtest/{{var4}}', dest: '/etc/prometheus/targets4.yml' }
      - { src: '/$HOME/ansible/pingtest/{{var5}}', dest: '/etc/prometheus/targets5.yml' }

  roles:
    - pingtest
