- hosts: parser-telkom
  strategy: free
  gather_facts: no
  become: true
  become_user: root
  vars:
    directories_to_check:
      - { directory: '/home/pamadmin/netsight_static/bandung-a/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/bandung-b/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/bandung-c/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/jakarta1-a/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/jakarta1-b/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/jakarta1-c/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/jakarta2-a/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/jakarta2-b/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/balikpapan-a/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/balikpapan-b/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/balikpapan-c/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/yogyakarta-a/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/yogyakarta-b/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/surabaya-a/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/surabaya-b/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/surabaya-c/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/pekanbaru-a/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/pekanbaru-b/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/pekanbaru-c/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/makassar-a/traceroute/', time: '-60' }
      - { directory: '/home/pamadmin/netsight_static/makassar-b/traceroute/', time: '-60' }


  roles:
    - database
