- hosts: parser-telkom
  strategy: free
  gather_facts: no
  become: true
  become_user: root
  vars:
    directories_to_check:
      - { directory: '/home/pamadmin/netsight_static/bandung-a/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/bandung-b/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/bandung-c/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/jakarta1-a/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/jakarta1-b/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/jakarta1-c/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/jakarta2-a/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/jakarta2-b/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/balikpapan-a/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/balikpapan-b/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/balikpapan-c/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/yogyakarta-a/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/yogyakarta-b/traceroute/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/surabaya-a/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/surabaya-b/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/surabaya-c/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/pekanbaru-a/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/pekanbaru-b/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/pekanbaru-c/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/makassar-a/streamvideo/', time: '-1500' }
      - { directory: '/home/pamadmin/netsight_static/makassar-b/streamvideo/', time: '-1500' }


  roles:
    - database
