- hosts: parser-mediation
  strategy: free
  gather_facts: no
  become: true
  become_user: root
  vars:
    directories_to_check:
      - { directory: '/home/netsightusr/netsight_remote/aws-hongkong/traceroute/', time: '-30' }
      - { directory: '/home/netsightusr/netsight_remote/aws-singapore/traceroute/', time: '-30' }
      - { directory: '/home/netsightusr/netsight_remote/aws-tokyo/traceroute/', time: '-30' }
      - { directory: '/home/netsightusr/netsight_remote/aws-ohio/traceroute/', time: '-30' }
      - { directory: '/home/netsightusr/netsight_remote/gcp-hongkong/traceroute/', time: '-30' }
      - { directory: '/home/netsightusr/netsight_remote/gcp-jakarta/traceroute/', time: '-30' }
      - { directory: '/home/netsightusr/netsight_remote/gcp-singapore/traceroute/', time: '-30' }
      - { directory: '/home/netsightusr/netsight_remote/gcp-tokyo/traceroute/', time: '-30' }

  roles:
    - database
